# Generated by Django 6.0.3 on 2026-03-22 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('spending_pattern', 'Spending Pattern'), ('expense_prediction', 'Expense Prediction'), ('anomaly_detection', 'Anomaly Detection'), ('recommendations', 'Recommendations')], max_length=30)),
                ('mongo_id', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'insights_insight',
                'ordering': ['-created_at'],
            },
        ),
    ]
