# Generated by Django 6.0.3 on 2026-03-22 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insight',
            name='content',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
